In [1]:
import numpy as np

from numpy import array
from numpy import diag
from numpy import zeros
from scipy.linalg import svd

In [2]:
# define a matrix
# A = array([
#     [1,2,3,4,5,6,7,8,9,10],
#     [11,12,13,14,15,16,17,18,19,20],
#     [21,22,23,24,25,26,27,28,29,30]
# ])
A = np.random.rand(3, 10)

print(A)

[[0.07352971 0.36044805 0.92218809 0.6933324  0.01706    0.28896906
  0.66900951 0.30337858 0.92602051 0.40826101]
 [0.36195974 0.50393622 0.94493427 0.24096444 0.81864482 0.81148075
  0.90106397 0.52624081 0.34721856 0.95763815]
 [0.26410602 0.83535665 0.23519039 0.98420093 0.61802359 0.75319248
  0.77073535 0.63055574 0.89370457 0.15482388]]


In [3]:
# Singular-value decomposition
U, s, VT = svd(A)

In [4]:
U, U.shape

(array([[-0.49139371,  0.21999216, -0.84269548],
        [-0.62148057, -0.7664303 ,  0.16231603],
        [-0.6101591 ,  0.60347994,  0.51333988]]), (3, 3))

In [5]:
s, s.shape

(array([3.26379328, 1.05890445, 0.82863366]), (3,))

In [6]:
VT, VT.shape

(array([[-0.12936777, -0.30639469, -0.36274334, -0.33426537, -0.27399031,
         -0.33883406, -0.41639034, -0.26376244, -0.37261313, -0.27276164],
        [-0.09619213,  0.1862158 , -0.35831319,  0.53053962, -0.23676952,
         -0.0980598 , -0.07394677,  0.04149737,  0.4504006 , -0.52008051],
        [ 0.15973871,  0.24965299, -0.60703923, -0.04818306,  0.52587647,
          0.33168716, -0.02638678,  0.18518553, -0.32006902, -0.13168957],
        [-0.57143733,  0.17856258,  0.18101128,  0.53718788,  0.12188165,
         -0.03073429, -0.16469972, -0.1057495 , -0.50058537,  0.12467751],
        [-0.0461877 , -0.59732353,  0.10047699,  0.16276523,  0.68120401,
         -0.20591991, -0.07573272, -0.09063919,  0.22886921, -0.17807081],
        [-0.20957138, -0.41306224,  0.03417827,  0.01659113, -0.20673157,
          0.83692655, -0.11189304, -0.09314386,  0.0436629 , -0.133153  ],
        [-0.36344481, -0.17537705, -0.21997858, -0.08737804, -0.05632905,
         -0.08789694,  0.8557023

In [7]:
# create m x n Sigma matrix
Sigma = zeros((A.shape[0], A.shape[1]))

In [8]:
Sigma, Sigma.shape

(array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]), (3, 10))

In [9]:
# populate Sigma with n x n diagonal matrix
Sigma[:A.shape[0], :A.shape[0]] = diag(s)

In [10]:
Sigma, Sigma.shape

(array([[3.26379328, 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ],
        [0.        , 1.05890445, 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.82863366, 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ]]),
 (3, 10))

In [11]:
# select
n_elements = 2
Sigma = Sigma[:, :n_elements]

In [12]:
Sigma, Sigma.shape

(array([[3.26379328, 0.        ],
        [0.        , 1.05890445],
        [0.        , 0.        ]]), (3, 2))

In [13]:
VT = VT[:n_elements, :]

In [14]:
VT, VT.shape

(array([[-0.12936777, -0.30639469, -0.36274334, -0.33426537, -0.27399031,
         -0.33883406, -0.41639034, -0.26376244, -0.37261313, -0.27276164],
        [-0.09619213,  0.1862158 , -0.35831319,  0.53053962, -0.23676952,
         -0.0980598 , -0.07394677,  0.04149737,  0.4504006 , -0.52008051]]),
 (2, 10))

In [15]:
# reconstruct
B = U.dot(Sigma.dot(VT))
print(B)

[[0.18507298 0.53477719 0.49830118 0.65968686 0.3842721  0.52058151
  0.650584   0.43269102 0.70252084 0.31630405]
 [0.3404748  0.47035776 1.02658137 0.24744509 0.74791416 0.76686865
  0.90461301 0.50133326 0.39026801 0.97535047]
 [0.19615785 0.72916158 0.4934071  1.00469659 0.39433114 0.61210248
  0.78195951 0.55178324 1.02985255 0.21084077]]


In [16]:
# transform
T = U.dot(Sigma)
print(T)

[[-1.60380749  0.23295067]
 [-2.0283841  -0.81157646]
 [-1.99143317  0.6390276 ]]


In [17]:
T = A.dot(VT.T)
print(T)

[[-1.60380749  0.23295067]
 [-2.0283841  -0.81157646]
 [-1.99143317  0.6390276 ]]
